version: '3'

vars:
  PROJECT: scraper
  ROOT_DIR:
    sh: pwd
  COMPOSE: PROJECT_PATH={{.ROOT_DIR}} docker compose -p {{.PROJECT}} --project-directory {{.ROOT_DIR}} -f {{.ROOT_DIR}}/compose.yml
  RUN_USER:
    sh: echo "--user $(id -u):$(id -g)"
  ENV_COMMON: -e TS_NODE_PROJECT=tsconfig.json

includes:
  viewer:
    taskfile: ./apps/viewer/Taskfile.yml
    dir: .
  ebook:
    taskfile: ./apps/ebook/Taskfile.yml
    dir: .
  obsidian:
    taskfile: ./apps/wiki/docker/obsidian/Taskfile.yml
    dir: .
  crawler:
    taskfile: ./apps/crawler/Taskfile.yml
    dir: .

  wiki:
    taskfile: ./apps/wiki/Taskfile.yml
    dir: .
  agents:
    taskfile: ./agents/Taskfile.yml
    dir: .
  joplin:
    taskfile: ./apps/wiki/docker/joplin/Taskfile.yml
    dir: .
  git:
    taskfile: ./agents/docker/gitea/Taskfile.yml
    dir: .
  meili:
    taskfile: ./infra/meilisearch/Taskfile.yml
    dir: .
  mongo:
    taskfile: ./infra/mongodb/Taskfile.yml
    dir: .
  redis:
    taskfile: ./infra/redis/Taskfile.yml
    dir: .
  traefik:
    taskfile: ./agents/docker/traefik/Taskfile.yml
    dir: .
  leantime:
    taskfile: ./agents/docker/leantime/Taskfile.yml
    dir: .

  usd:
    taskfile: ./projects/LearnOpenUSD/Taskfile.yml
    dir: .

tasks:
  config:
    desc: Validate the full Docker Compose graph.
    summary: |
      Validate the full Docker Compose graph and print resolved service structure.
      
      [Usage Examples]
        - task config
    cmds:
      - '{{.COMPOSE}} config'



