services:
  ebook:
    build:
      context: ${PROJECT_PATH:-.}/projects/ebook
      dockerfile: docker/Dockerfile
    platform: linux/${ARCH:-arm64}
    image: ebook:${ARCH:-arm64}
    environment:
      - TZ=${TZ:-Asia/Seoul}
      - MONGO_URL=${MONGO_URL:-mongodb://mongodb:27017}
    volumes:
      - ${PROJECT_PATH:-.}/data/ebook:/app/data
    restart: "no"
