version: '3'

tasks:
  ps:
    desc: Show Obsidian container status.
    summary: |
      Display the current status of the Obsidian container.

      [Usage Examples]
        - task obsidian:ps
    cmds:
      - '{{.COMPOSE}} ps obsidian'
