version: '3'

tasks:
  config:
    cmds:
      - '{{.COMPOSE}} config'
  up:
    desc: Start Redis server.
    cmds:
      - '{{.COMPOSE}} up -d redis'
  gui:up:
    desc: Start RedisInsight web UI.
    cmds:
      - '{{.COMPOSE}} --profile tools up -d redisinsight'
  down:
    desc: Stop Redis and RedisInsight.
    cmds:
      - '{{.COMPOSE}} stop redis redisinsight'


